//Test evaluating answer "true" for the colors 
var color1 = "red";
console.log("Is the color of apple ".concat(color1, "? I predict true."));
console.log(color1 === "red");
var color2 = "purple";
console.log("Is the color of the bag ".concat(color2, "? I predict true."));
console.log(color2 === "purple");
var color3 = "black";
console.log("Is ".concat(color3, " darkest color and achromatic? I predict true."));
console.log(color3 === "black");
var color4 = "green";
console.log("Is ".concat(color4, " the color of our national flag? I predict true."));
console.log(color4 === "green");
var color5 = "white";
console.log("are clouds ".concat(color5, " in color? I predict true."));
console.log(color5 === "white");
//Tests evaluating answer "false" on the scenario : Pakistan
var capital = "Lahore";
console.log("Is the capital of Pakistan \"".concat(capital, "\"? I predict false."));
console.log(capital === "Islamabad");
var officialLanguage = "English";
console.log("Is the official language of Pakistan  \"".concat(officialLanguage, "\"? I predict false."));
console.log(officialLanguage === "Urdu");
var highestPeak = "K2";
console.log("Is the highest peak in Pakistan \"".concat(highestPeak, "\"? I predict false."));
console.log(highestPeak === "Nanga Parbat");
var nationalSport = "Cricket";
console.log("Is the national sport of Pakistan \"".concat(nationalSport, "\"? I predict false."));
console.log(nationalSport === "Hockey");
var currency = "Dollar";
console.log("Is the currency of Pakistan \"".concat(currency, "\"? I predict false."));
console.log(currency === "Pakistani Rupee");
